### ISSUE TITLE
Players are still getting stuck in trap rooms because of disconnected players

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/pathfinder_issues#130] opened 2021-11-05 02:06 UTC
![image](https://user-images.githubusercontent.com/63279022/140446198-e6fd1904-9e83-4f2e-8683-dad007d07a28.png)

**Comment by Draze22** [comment] 2021-11-09 01:31
![image](https://user-images.githubusercontent.com/63279022/140845221-35cd1f55-f1bc-48f5-9a9f-d8e8c4ed926c.png)

**Comment by fcalife** [comment] 2021-11-12 08:11
duplicate of https://github.com/arcadia-redux/pathfinder_issues/issues/114

**Closed by fcalife** 2021-11-12 08:11 UTC
Labels: bug
