### ISSUE TITLE
Short descriptions that pop up whenever players hover over a difficulty statue

### ISSUE THREAD

**Issue by Snoresville** [arcadia-redux/pathfinder_issues#20] opened 2021-10-15 13:24 UTC
Would have short descriptions of what to expect when choosing a specific difficulty

at the top of my head, it would list the base number of enemy modifiers per level and the multiplier of arcane fragments

**Comment by ZLOY5** [comment] 2021-10-16 14:21
Duplicate of https://github.com/arcadia-redux/pathfinder_issues/issues/59

**Closed by ZLOY5** 2021-10-16 14:21 UTC
Labels: enhancement
